import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Loader2, FileText, Dna } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { PageContainer } from "@/components/layout/PageContainer";
import { UploadZone } from "@/components/UploadZone";
import { useAnalysisResult } from "@/contexts/AnalysisResultContext";
import { analyzeVcf, mapApiResponseToResult } from "@/lib/api";

/** Strict scope: only these 6 drugs (backend enforces). */
const ALLOWED_DRUGS = [
  "CODEINE",
  "WARFARIN",
  "CLOPIDOGREL",
  "SIMVASTATIN",
  "AZATHIOPRINE",
  "FLUOROURACIL",
] as const;

type ExplanationMode = "clinician" | "research";

const Analysis = () => {
  const navigate = useNavigate();
  const { setResultAndApi } = useAnalysisResult();
  const [file, setFile] = useState<File | null>(null);
  const [drug, setDrug] = useState<string>("");
  const [explanationMode, setExplanationMode] = useState<ExplanationMode>("clinician");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const handleAnalyze = async () => {
    if (!file) {
      setError("Please upload a VCF file.");
      return;
    }
    const drugName = drug.trim().toUpperCase();
    if (!ALLOWED_DRUGS.includes(drugName as (typeof ALLOWED_DRUGS)[number])) {
      setError("Please select a drug from the list.");
      return;
    }
    setError("");
    setLoading(true);
    try {
      const apiResponse = await analyzeVcf(file, drugName, undefined, explanationMode);
      const result = mapApiResponseToResult(apiResponse, file.name);
      setResultAndApi(result, apiResponse);
      navigate("/results");
    } catch (e) {
      console.error(e);
      setError(e instanceof Error ? e.message : "Analysis failed. Check the file and try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <DashboardLayout>
      <PageContainer>
        <div className="fade-in-up mx-auto max-w-lg pt-8 sm:pt-16">
          <div className="mb-8 text-center">
            <h1 className="mb-2 text-2xl font-bold text-foreground">Patient Analysis</h1>
            <p className="text-sm text-muted-foreground">
              Upload a VCF file and select a drug. Analysis runs on the backend (CPIC rule engine); AI explanation is generated by the API.
            </p>
          </div>

          <div className="clinical-card space-y-6">
            <div className="space-y-2">
              <div className="flex items-center gap-2">
                <FileText className="h-4 w-4 text-primary" />
                <label className="text-xs font-medium uppercase tracking-wider text-muted-foreground">
                  Genetic data (VCF)
                </label>
              </div>
              <UploadZone onFileSelect={(f) => { setFile(f); setError(""); }} />
            </div>

            {file && (
              <div className="fade-in flex items-center gap-2 rounded-xl bg-success/10 px-4 py-2.5 text-sm text-success">
                <span className="h-1.5 w-1.5 rounded-full bg-success" />
                {file.name}
              </div>
            )}

            <div className="space-y-2">
              <div className="flex items-center gap-2">
                <Dna className="h-4 w-4 text-primary" />
                <label className="text-xs font-medium uppercase tracking-wider text-muted-foreground">
                  Drug
                </label>
              </div>
              <Select value={drug} onValueChange={(v) => { setDrug(v); setError(""); }}>
                <SelectTrigger className="rounded-xl">
                  <SelectValue placeholder="Select a drug" />
                </SelectTrigger>
                <SelectContent>
                  {ALLOWED_DRUGS.map((d) => (
                    <SelectItem key={d} value={d}>
                      {d.charAt(0) + d.slice(1).toLowerCase()}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <label className="text-xs font-medium uppercase tracking-wider text-muted-foreground">
                AI explanation mode
              </label>
              <div className="flex gap-2">
                <Button
                  type="button"
                  variant={explanationMode === "clinician" ? "default" : "outline"}
                  size="sm"
                  className="rounded-xl flex-1"
                  onClick={() => setExplanationMode("clinician")}
                >
                  Clinician
                </Button>
                <Button
                  type="button"
                  variant={explanationMode === "research" ? "default" : "outline"}
                  size="sm"
                  className="rounded-xl flex-1"
                  onClick={() => setExplanationMode("research")}
                >
                  Research
                </Button>
              </div>
              <p className="text-xs text-muted-foreground">
                {explanationMode === "clinician"
                  ? "Short, action-focused explanation."
                  : "Detailed mechanism, variant impact, PK."}
              </p>
            </div>

            {error && (
              <div className="fade-in rounded-xl bg-destructive/10 px-4 py-2.5 text-sm text-destructive">
                {error}
              </div>
            )}

            <Button
              onClick={handleAnalyze}
              disabled={loading}
              className="w-full rounded-xl py-5 text-sm font-semibold shadow-sm transition-all duration-200 hover:shadow-md"
            >
              {loading ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Analyzing…
                </>
              ) : (
                "Analyze"
              )}
            </Button>
          </div>
        </div>
      </PageContainer>
    </DashboardLayout>
  );
};

export default Analysis;
